Imagine a service which retrieves headlines for a given month. This operation may be expensive and you may want to cache it.

[source, kotlin]
.src/main/kotlin/example/micronaut/NewsService.kt
----
include::{sourceDir}/src/main/kotlin/example/micronaut/NewsService.kt[]
----

<1> To register a Singleton in Micronaut’s application context annotate your class with `javax.inject.Singleton`.
<2> Specifies the cache name `headlines` to store cache operation values in.
<3> Indicates a method is cacheable. The cache name `headlines` specified in `@CacheConfig` is used. Since the method has only one parameter, you don't need to specify the `month` parameters attribute of the the annation.
<4> Emulate an expensive operation by sleeping for several seconds.
<5> The return value is cached with name `headlines` for the supplied `month`. The method invocation is never skipped even if the cache `headlines` for the supplied `month` already existed.
<6> Method invocation causes the invalidation of the cache `headlines` for the supplied `month`.

TIP: If you don't annotate the class with `@CacheConfig`, specify the cache name in the cache annotations. E.g. `@Cacheable(value = "headlines", parameters = {"month"})`